# Generated by Django 5.2.7 on 2025-11-07 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_file', models.FileField(upload_to='uploads/audio/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Text content to be used in email body')),
                ('audio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email', to='core.audiofile')),
            ],
        ),
        migrations.CreateModel(
            name='ImportantPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_points', to='core.audiofile')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('audio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='core.audiofile')),
            ],
        ),
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_done', models.BooleanField(default=False)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='core.audiofile')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.CharField(help_text='Start time (e.g., 00:00:03)', max_length=50)),
                ('end_time', models.CharField(help_text='End time (e.g., 00:00:08)', max_length=50)),
                ('text', models.TextField()),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='core.audiofile')),
            ],
        ),
    ]
