# Generated by Django 5.2.7 on 2025-11-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantpoint',
            name='is_added_to_calendar',
            field=models.BooleanField(default=False),
        ),
    ]
